-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 19:50:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `cursos`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS` (
  `idCURSO` INT NOT NULL AUTO_INCREMENT,
  `NombreCurso` VARCHAR(35) NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `Localidad` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `NumPlazas` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `Imagen` BLOB NULL,
  PRIMARY KEY (`idCURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`ESTUDIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESTUDIANTES` (
  `idESTUDIANTES` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(25) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`idESTUDIANTES`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`CURSOS_has_ESTUDIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CURSOS_has_ESTUDIANTES` (
  `CURSOS_idCURSOS` INT NOT NULL,
  `ESTUDIANTES_idESTUDIANTES` INT NOT NULL,
  PRIMARY KEY (`CURSOS_idCURSOS`, `ESTUDIANTES_idESTUDIANTES`),
  INDEX `fk_CURSOS_has_ESTUDIANTES_ESTUDIANTES1_idx` (`ESTUDIANTES_idESTUDIANTES` ASC),
  INDEX `fk_CURSOS_has_ESTUDIANTES_CURSOS1_idx` (`CURSOS_idCURSOS` ASC),
  CONSTRAINT `fk_CURSOS_has_ESTUDIANTES_CURSOS1`
    FOREIGN KEY (`CURSOS_idCURSOS`)
    REFERENCES `CURSOS` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSOS_has_ESTUDIANTES_ESTUDIANTES1`
    FOREIGN KEY (`ESTUDIANTES_idESTUDIANTES`)
    REFERENCES `ESTUDIANTES` (`idESTUDIANTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`HORARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HORARIOS` (
  `idHORARIOS` INT NOT NULL AUTO_INCREMENT,
  `Dia` VARCHAR(10) NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `HoraFin` VARCHAR(45) NOT NULL,
  `idCURSO` INT NOT NULL,
  PRIMARY KEY (`idHORARIOS`),
  INDEX `fk_HORARIOS_CURSOS1_idx` (`idCURSO` ASC),
  CONSTRAINT `fk_HORARIOS_CURSOS1`
    FOREIGN KEY (`idCURSO`)
    REFERENCES `CURSOS` (`idCURSO`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
